settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: auth
  path: .
  commands:
    vet:
        status: true
    fmt:
        status: true
        args:
        - -s
        - -w
    generate:
        status: true
    install:
        status: true
    build:
        status: false
        args:
        - -race
    run:
        status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    ignored_paths:
    - .git
    - .realize
    - vendor
