version: '3.1'
services:
  db:
    image: postgres:10.1
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
