settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5002
  host: localhost
schema:
- name: adify
  path: ./cmd/adify
  commands:
    vet:
        status: false
    fmt:
        status: true
        args:
        - -s
        - -w
    generate:
        status: false
    install:
        status: true
    build:
        status: false
        args:
        - -race
    run:
        status: true
  watcher:
    paths:
    - ../../
    extensions:
    - go
    ignored_paths:
    - ../../vendor
